{
 "title": "Email Service Observability",
 "tags": [
  "email",
  "observability"
 ],
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "Requests per Minute",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 6, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "rate(email_process_duration_seconds_count[5m]) * 60"
    }
   ]
  },
  {
   "title": "Error Rate %",
   "type": "stat",
   "description": "Alert if > 5.0 %",
   "gridPos": { "h": 7, "w": 4, "x": 6, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "rate(email_process_final_failure_total[5m]) / (rate(email_process_success_total[5m]) + rate(email_process_final_failure_total[5m])) * 100"
    }
   ]
  },
  {
   "title": "Process Success vs Failure",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 6, "x": 10, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "req/s" } },
   "targets": [
    {
     "expr": "sum(rate(email_process_duration_seconds_count[5m])) by (status)",
     "legendFormat": "{{status}}"
    }
   ]
  },
  {
   "title": "P95 Process Latency",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum(rate(email_process_duration_seconds_bucket[5m])) by (le))"
    }
   ]
  },
  {
   "title": "P99 Process Latency",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.99, sum(rate(email_process_duration_seconds_bucket[5m])) by (le))"
    }
   ]
  },
  {
   "title": "DQL counter",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 8, "x": 0, "y": 15 },
   "targets": [
    {
     "expr": "increase(email_process_final_failure_total[15m])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "SMTP Sending Latency (P95)",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 8, "x": 8, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum(rate(email_send_duration_seconds_bucket[5m])) by (le))"
    }
   ]
  }
 ]
}